theme: jekyll-theme-minimal
title: Nithilan's homepage
description: A website to show my joy in learning physics and spreading it to the world. Helping other students in the process.

# Book configuration
disablePathToLower: true
enableGitInfo: true
